[package]
name = "reth-nippy-jar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Immutable data store format"

[lib]
name = "reth_nippy_jar"

[dependencies]
memmap2 = "0.7.1"
bloomfilter = "1"
zstd = { version = "0.12", features = ["experimental", "zdict_builder"] }
ph = "0.8.0"
thiserror = "1.0"
bincode = "1.3"
serde = { version = "1.0",  features = ["derive"] }
bytes = "1.5"
cuckoofilter = { version = "0.5.0", features = ["serde_support", "serde_bytes"] }
tempfile = "3.4"
sucds = "~0.8"

anyhow = "1.0"


[dev-dependencies]
rand = { version = "0.8", features = ["small_rng"] }


[features]
default = []