[package]
name = "reth-rlp-derive"
version.workspace = true
license = "Apache-2.0"
edition.workspace = true
rust-version.workspace = true
description = "Procedural macros for reth-rlp"
homepage.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote.workspace = true
proc-macro2.workspace = true
